import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import AppTopBar from '@/app/ui/AppTopBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <AppRouterCacheProvider options={{ key: 'css' }}>
            <body className={inter.className}>
            <AppTopBar />
            <main>{children}</main>
            </body>
        </AppRouterCacheProvider>
        </html>
    );
}
